// Список наиболее используемых гомеопатических препаратов
// Используется для автодополнения при назначении и выборе конституционального типа

export const HOMEOPATHIC_REMEDIES: string[] = [
  'Aconitum napellus',
  'Aesculus hippocastanum',
  'Aethusa cynapium',
  'Agnus castus',
  'Allium cepa',
  'Alumina',
  'Ambra grisea',
  'Ammonium carbonicum',
  'Ammonium muriaticum',
  'Anacardium orientale',
  'Antimonium crudum',
  'Antimonium tartaricum',
  'Apis mellifica',
  'Argentum metallicum',
  'Argentum nitricum',
  'Arnica montana',
  'Arsenicum album',
  'Arsenicum iodatum',
  'Aurum metallicum',
  'Aurum muriaticum',
  'Baptisia tinctoria',
  'Baryta carbonica',
  'Baryta muriatica',
  'Belladonna',
  'Bellis perennis',
  'Borax',
  'Bromium',
  'Bryonia alba',
  'Bufo rana',
  'Calcarea carbonica',
  'Calcarea fluorica',
  'Calcarea phosphorica',
  'Calcarea silicata',
  'Calcarea sulphurica',
  'Calendula officinalis',
  'Camphora',
  'Cannabis indica',
  'Cannabis sativa',
  'Cantharis',
  'Carbo animalis',
  'Carbo vegetabilis',
  'Carcinosinum',
  'Causticum',
  'Chamomilla',
  'Chelidonium majus',
  'China (Cinchona officinalis)',
  'Cimicifuga (Actaea racemosa)',
  'Cina maritima',
  'Clematis erecta',
  'Cocculus indicus',
  'Coffea cruda',
  'Colocynthis',
  'Conium maculatum',
  'Crocus sativus',
  'Crotalus horridus',
  'Cuprum metallicum',
  'Digitalis purpurea',
  'Dioscorea villosa',
  'Drosera rotundifolia',
  'Dulcamara',
  'Eupatorium perfoliatum',
  'Euphrasia officinalis',
  'Ferrum metallicum',
  'Ferrum phosphoricum',
  'Fluoric acid (Fluoricum acidum)',
  'Gelsemium sempervirens',
  'Glonoine',
  'Graphites',
  'Gratiola officinalis',
  'Hamamelis virginiana',
  'Helleborus niger',
  'Hepar sulphuris calcareum',
  'Hydrastis canadensis',
  'Hyoscyamus niger',
  'Hypericum perforatum',
  'Ignatia amara',
  'Iodum',
  'Ipecacuanha',
  'Iris versicolor',
  'Kali arsenicum',
  'Kali bichromicum',
  'Kali bromatum',
  'Kali carbonicum',
  'Kali iodatum',
  'Kali muriaticum',
  'Kali nitricum',
  'Kali phosphoricum',
  'Kali sulphuricum',
  'Kreosotum',
  'Lac caninum',
  'Lac defloratum',
  'Lachesis mutus',
  'Lachnanthes tinctoria',
  'Ledum palustre',
  'Lilium tigrinum',
  'Luesinum (Syphilinum)',
  'Lycopodium clavatum',
  'Lycopus virginicus',
  'Magnesia carbonica',
  'Magnesia muriatica',
  'Magnesia phosphorica',
  'Medorrhinum',
  'Mercurius corrosivus',
  'Mercurius iodatus flavus',
  'Mercurius iodatus ruber',
  'Mercurius solubilis',
  'Mezereum',
  'Millefolium',
  'Muriaticum acidum',
  'Natrum carbonicum',
  'Natrum muriaticum',
  'Natrum phosphoricum',
  'Natrum sulphuricum',
  'Nitricum acidum',
  'Nux moschata',
  'Nux vomica',
  'Opium',
  'Palladium metallicum',
  'Petroleum',
  'Phosphoricum acidum',
  'Phosphorus',
  'Phytolacca decandra',
  'Platinum metallicum',
  'Plumbum metallicum',
  'Podophyllum peltatum',
  'Psorinum',
  'Pulsatilla nigricans',
  'Ranunculus bulbosus',
  'Rheum officinale',
  'Rhododendron',
  'Rhus toxicodendron',
  'Robinia pseudoacacia',
  'Rumex crispus',
  'Ruta graveolens',
  'Sabadilla',
  'Sabina',
  'Sambucus nigra',
  'Sanguinaria canadensis',
  'Sarsaparilla',
  'Secale cornutum',
  'Selenium metallicum',
  'Sepia officinalis',
  'Silicea',
  'Spigelia anthelmia',
  'Spongia tosta',
  'Stannum metallicum',
  'Staphysagria',
  'Sticta pulmonaria',
  'Stramonium',
  'Sulphur',
  'Sulphuricum acidum',
  'Symphytum officinale',
  'Syphilinum (Luesinum)',
  'Tabacum',
  'Tarentula hispanica',
  'Teucrium marum',
  'Thuja occidentalis',
  'Tuberculinum',
  'Tuberculinum bovinum',
  'Urtica urens',
  'Ustilago maydis',
  'Valeriana officinalis',
  'Veratrum album',
  'Veratrum viride',
  'Viola tricolor',
  'Zincum metallicum',
  'Zincum phosphoricum',
].sort()

// Поиск по списку — возвращает до maxResults совпадений
export function searchRemedies(query: string, maxResults = 8): string[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  return HOMEOPATHIC_REMEDIES.filter(r => r.toLowerCase().includes(q)).slice(0, maxResults)
}

// Основные конституциональные типы (полихресты)
export const CONSTITUTIONAL_TYPES = [
  'Argentum nitricum',
  'Arsenicum album',
  'Aurum metallicum',
  'Baryta carbonica',
  'Calcarea carbonica',
  'Calcarea phosphorica',
  'Calcarea silicata',
  'Causticum',
  'Graphites',
  'Ignatia amara',
  'Kali carbonicum',
  'Lachesis mutus',
  'Lycopodium clavatum',
  'Medorrhinum',
  'Mercurius solubilis',
  'Natrum carbonicum',
  'Natrum muriaticum',
  'Nitricum acidum',
  'Nux vomica',
  'Phosphorus',
  'Psorinum',
  'Pulsatilla nigricans',
  'Sepia officinalis',
  'Silicea',
  'Staphysagria',
  'Sulphur',
  'Thuja occidentalis',
  'Tuberculinum',
]
