import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://obcbinbhurokubvbsgjx.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iY2JpbmJodXJva3VidmJzZ2p4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzU5MTM4OSwiZXhwIjoyMDg5MTY3Mzg5fQ.e7g4Dlm8npJkTNbE3Ak79WFEHHImVGKJhsTUpOAfF5g'
)

const ruNames = {
  'Acon.':     'Аконит',
  'Agar.':     'Агарикус',
  'Agn.':      'Агнус',
  'All-c.':    'Аллиум цепа',
  'Alum.':     'Алюмина',
  'Am-c.':     'Аммоний карб',
  'Am-m.':     'Аммоний мур',
  'Anac.':     'Анакардиум',
  'Ant-c.':    'Антимониум круд',
  'Ant-t.':    'Антимониум тарт',
  'Apis.':     'Апис',
  'Arg-m.':    'Аргентум мет',
  'Arg-n.':    'Аргентум нитрикум',
  'Arn.':      'Арника',
  'Ars.':      'Арсеникум',
  'Ars-i.':    'Арсеникум йод',
  'Aur.':      'Аурум',
  'Aur-m.':    'Аурум мур',
  'Bar-c.':    'Барита карб',
  'Bar-m.':    'Барита мур',
  'Bell.':     'Белладонна',
  'Bor.':      'Бора',
  'Bry.':      'Бриония',
  'Calc.':     'Кальк карб',
  'Calc-f.':   'Кальк фтор',
  'Calc-p.':   'Кальк фос',
  'Calc-s.':   'Кальк сульф',
  'Calc-sil.': 'Кальк сил',
  'Calen.':    'Календула',
  'Camph.':    'Камфора',
  'Cann-i.':   'Каннабис инд',
  'Canth.':    'Кантарис',
  'Carb-an.':  'Карбо аним',
  'Carb-v.':   'Карбо вег',
  'Carc.':     'Карциносин',
  'Caust.':    'Каустикум',
  'Cham.':     'Ромашка / Камомилла',
  'Chel.':     'Хелидониум',
  'Chin.':     'Хина / China',
  'Cimic.':    'Цимицифуга',
  'Cina.':     'Цина',
  'Coc-c.':    'Коккулюс',
  'Coff.':     'Кофея',
  'Coloc.':    'Колоцинт',
  'Con.':      'Кониум',
  'Cupr.':     'Купрум',
  'Dig.':      'Дигиталис',
  'Dros.':     'Дрозера',
  'Dulc.':     'Дулкамара',
  'Euphr.':    'Эуфразия',
  'Ferr.':     'Феррум',
  'Ferr-p.':   'Феррум фос',
  'Fl-ac.':    'Флуорикум ацид',
  'Gels.':     'Гельземиум',
  'Glon.':     'Глонин',
  'Graph.':    'Графит',
  'Ham.':      'Гамамелис',
  'Hell.':     'Хеллеборус / Морозник',
  'Hep.':      'Гепар сульфур',
  'Hyos.':     'Хиосциамус',
  'Hyper.':    'Гиперикум / Зверобой',
  'Ign.':      'Игнация',
  'Iod.':      'Йодум',
  'Ip.':       'Ипекакуана',
  'Kali-ar.':  'Кали арс',
  'Kali-bi.':  'Кали бихром',
  'Kali-br.':  'Кали бром',
  'Kali-c.':   'Кали карб',
  'Kali-i.':   'Кали йод',
  'Kali-m.':   'Кали мур',
  'Kali-n.':   'Кали нитр',
  'Kali-p.':   'Кали фос',
  'Kali-s.':   'Кали сульф',
  'Kreos.':    'Креозот',
  'Lac-c.':    'Лак канинум',
  'Lach.':     'Лахезис',
  'Led.':      'Ледум',
  'Lyc.':      'Ликоподиум',
  'Mag-c.':    'Магнезия карб',
  'Mag-m.':    'Магнезия мур',
  'Mag-p.':    'Магнезия фос',
  'Med.':      'Медорринум',
  'Merc.':     'Меркуриус',
  'Merc-c.':   'Меркуриус корр',
  'Mez.':      'Мезереум',
  'Mur-ac.':   'Муриатикум ацид',
  'Nat-c.':    'Натрум карб',
  'Nat-m.':    'Натрум мур',
  'Nat-p.':    'Натрум фос',
  'Nat-s.':    'Натрум сульф',
  'Nit-ac.':   'Нитрикум ацид',
  'Nux-m.':    'Нукс мошата',
  'Nux-v.':    'Нукс вомика / Чилибуха',
  'Op.':       'Опиум',
  'Petr.':     'Петролеум',
  'Ph-ac.':    'Фосфорикум ацид',
  'Phos.':     'Фосфор',
  'Phyt.':     'Фитолакка',
  'Plat.':     'Платина',
  'Plb.':      'Плюмбум',
  'Psor.':     'Псорин',
  'Puls.':     'Пульсатилла / Прострел',
  'Rhod.':     'Рододендрон',
  'Rhus-t.':   'Рус токс',
  'Ruta.':     'Рута',
  'Sabad.':    'Сабадилла',
  'Sang.':     'Сангвинария',
  'Sep.':      'Сепия',
  'Sil.':      'Силиция',
  'Spig.':     'Спигелия',
  'Spong.':    'Спонгия',
  'Stann.':    'Станнум',
  'Staph.':    'Стафизагрия',
  'Stram.':    'Страмониум / Дурман',
  'Sul-ac.':   'Сульфурикум ацид',
  'Sulph.':    'Сульфур / Сера',
  'Symph.':    'Симфитум / Окопник',
  'Syph.':     'Сифилинум',
  'Tab.':      'Табакум',
  'Tarent.':   'Тарентула',
  'Thuj.':     'Туя',
  'Tub.':      'Туберкулинум',
  'Valer.':    'Валериана',
  'Verat.':    'Вератрум альб',
  'Zinc.':     'Цинкум',
  'Zinc-p.':   'Цинкум фос',
}

let ok = 0, err = 0
for (const [abbrev, name_ru] of Object.entries(ruNames)) {
  const { error } = await supabase
    .from('homeo_remedies')
    .update({ name_ru })
    .eq('abbrev', abbrev)
  if (error) { err++; console.error(`Ошибка ${abbrev}:`, error.message) }
  else ok++
}

console.log(`✓ Обновлено: ${ok}, ошибок: ${err}`)

// Проверка
const { data } = await supabase
  .from('homeo_remedies')
  .select('abbrev, name_latin, name_ru')
  .not('name_ru', 'is', null)
  .limit(5)
console.log('Примеры:', data)
